spring:
  ip: 127.0.0.1
  rabbitmq:
    host: 113.44.139.100 #主机名
    port: 5672  # 消息发送接收端口
    virtual-host: pigchat #虚拟主机
    username: linjunyi #用户名
    password: linjunyi3676 #密码
    listener:
      simple:
        prefetch: 1  # 每个消费者每次处理一条消息，处理完才能接收下一条消息，而不是轮询的模式
  web:
    resources:
      static-locations: classpath:/public/,classpath:/static/
  data:
    mongodb:
      # 主机地址
      host: 113.44.139.100
      # 数据库
      database: pigchat
      # 端口号，默认为27017
      port: 27017
      # 用户名
      username: linjunyi
      # 密码
      password: linjunyi
      # 认证数据库，通常与目标数据库相同
      authentication-database: admin
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false  # 是否允许清空监控数据
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: pigchat1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://113.44.139.100:3306/pigchat?useSSL=false&serverTimezone=UTC
mybatis-plus:
  type-aliases-package: pig.chat.springboot.domain     #别名扫描包
  mapper-locations: "classpath*:/mapper/**/*.xml"       # Mapper.xml文件地址
  configuration:
    map-underscore-to-camel-case: true      # 是否开启下划线和驼峰的映射
    cache-enabled: false    #是否开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #开启日志打印
  global-config:
    db-config:
      id-type: assign_id    # id为雪花算法自动生成
      update-strategy: not_null   #更新策略，只更新非空字段
server:
  port: 8008


