spring:
  data:
    mongodb:
      # 主机地址
      host: 127.0.0.1
      # 数据库
      database: store
      # 端口号，默认为27017
      port: 27017
      # 也可以使用uri连接
      uri: mongodb://127.0.0.1:27017/pigchat
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pigchat?useSSL=false&serverTimezone=UTC
mybatis-plus:
  type-aliases-package: pig.chat.springboot.domain     #别名扫描包
  mapper-locations: "classpath*:/mapper/**/*.xml"       # Mapper.xml文件地址
  configuration:
    map-underscore-to-camel-case: true      # 是否开启下划线和驼峰的映射
    cache-enabled: false    #是否开启二级缓存
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #开启日志打印
  global-config:
    db-config:
      id-type: assign_id    # id为雪花算法自动生成
      update-strategy: not_null   #更新策略，只更新非空字段
server:
  port: 8008


